# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andrew', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('level', models.DecimalField(choices=[(1.0, 1.0), (2.0, 2.0)], decimal_places=1, max_digits=2)),
                ('frequency', models.IntegerField(choices=[(1, 'Once/ week'), (2, 'Twice/ week'), (3, 'Three times/ week')])),
            ],
        ),
    ]
