# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='times',
            field=models.CharField(choices=[('MM', 'Monday Morning'), ('MA', 'Monday Afternoon'), ('MN', 'Monday Night'), ('TM', 'Tuesday Morning'), ('TA', 'Tuesday Afternoon'), ('TN', 'Tuesday Night'), ('WM', 'Wednesday Morning'), ('WA', 'Wednesday Afternoon'), ('WN', 'Wednesday Night'), ('TrM', 'Thursday Morning'), ('TrA', 'Thursday Afternoon'), ('TrN', 'Thursday Night'), ('FM', 'Friday Morning'), ('FA', 'Friday Afternoon'), ('FN', 'Friday Night'), ('SM', 'Saturday Morning'), ('SA', 'Saturday Afternoon'), ('SN', 'Saturday Night'), ('SuM', 'Sunday Morning'), ('SuA', 'Sunday Afternoon'), ('SuN', 'Sunday Night')], default='None', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Once/ week'), (2, 'Twice/ week'), (3, 'Three times/ week'), (4, 'Four times/ week'), (5, 'Five times/ week'), (6, 'Six times/ week'), (7, 'Everyday')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0), (5.5, 5.5), (6.0, 6.0)], decimal_places=1, max_digits=2),
        ),
    ]
