# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161122_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
