# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161124_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
