# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161124_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='times',
            field=models.TextField(),
        ),
    ]
