# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matchHistoryByOpponent',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='player',
            name='matchHistoryByTime',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default='None'),
        ),
    ]
