# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161205_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='matchHistoryByOpponent',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='matchHistoryByTime',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=None),
        ),
    ]
