# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161205_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='matchHistoryByOpponent',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='player',
            name='matchHistoryByTime',
            field=models.TextField(default='None'),
        ),
    ]
