# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161205_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matchHistoryByOpponent',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matchHistoryByTime',
        ),
    ]
