# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matchHistoryByOpponent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='matchHistoryByTime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
